// Generated by scripts/analyze-beats.js — do not edit by hand.
// Re-run the script after replacing any file in music/. Tracks whose
// onsets do not lock to one constant grid are omitted here on purpose:
// the spawner falls back to its legacy pacing for those tracks.
export interface Beatmap {
  readonly bpm: number
  // seconds from track start to the first downbeat's onset
  readonly offset: number
}

export const BEATMAPS: Record<string, Beatmap> = {
  'grid-pressure.mp3': { bpm: 140, offset: 0.399 },
  'grid-runner-pulse.mp3': { bpm: 150.34, offset: 0.284 },
  // 'bgm.mp3' excluded: grid ratio 1.49 < 1.5; kick strength on grid 37% < 45%
  // 'gravity-coin-alt.mp3' excluded: grid ratio 1.20 < 1.5; kick strength on grid 39% < 45%
  // 'gravity-coin.mp3' excluded: grid ratio 1.37 < 1.5; kick strength on grid 38% < 45%; segment phase drift 199ms > 55ms
}
